name: "\U0001F41E Bug report"
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["\U0001F41E bug"]
body:
  - type: markdown
    attributes:
      value: |
        - Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean.
        - Have a look at ["I want to file an issue!"][info] for more information.
# TODO: Change info of issue guide.
        [info]: https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. Click on...
        2. Go to...
        3. Go back...
        4. Observe...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: Files successfully downloads...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      placeholder: The app closes unexpectedly...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Device information
  - type: input
    attributes:
      label: Device name
      description: The name of the device model and manufacturer.
      placeholder: Google Pixel 6
    validations:
      required: false
  - type: input
    attributes:
      label: Android version
      description: You can find the Android version information in the About section of your device's system settings.
      placeholder: Android 10
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Bottle variant
      description: You can find this information in Settings -> About Bottle.
      options:
        - Bottle Beta
        - Bottle
    validations:
      required: true
  - type: input
    attributes:
      label: Bottle version
      description: You can find this information in Settings -> About Bottle.
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device logs
      description: |
        Device logs or crash information can greatly aid in debugging. You can find some details here on how to [retrieve device logs or crash IDs][log].

        [log]: https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
    validations:
      required: false